let PICADAS = [
    {"id": "01",
     "nombre": "Clásica",
     "imagen": "images/tabla1.jpg",
     "miniaturas": ["images/tabla1.jpg", "images/tabla3extra.jpg","images/tabla4extra.jpg"],
     "cantidad": "Comen 3, Pican 6",
     "ingredientes": "Jamon crudo, Mar del Plata, Jamon cocido, Pategrás, Spianatta, Gruyere, Mortadela, Salame Milán",
     "comentario": "",
     "precio": 1170,
     "cantidadComprada": 0},
     {"id": "02",
     "nombre": "De Campo",
     "imagen": "images/tabla2.jpg",
     "miniaturas": ["images/tabla2.jpg", "images/tabla3extra.jpg","images/tabla4extra.jpg"],
     "cantidad": "Comen 3, Pican 8",
     "ingredientes": "Jamon crudo, Lomo horneado, Bondiola, Salame tandilero, Leber, Mar del Plata, Queso Condimentado, Roquefort, Brie",
     "comentario": "",
     "precio": 1550,
     "cantidadComprada": 0},
     {"id": "03",
     "nombre": "Parma",
     "imagen": "images/tabla3.jpg",
     "miniaturas": ["images/tabla3.jpg", "images/tabla1extra.jpg","images/tabla4extra.jpg"],
     "cantidad": "Comen 4, Pican 8",
     "ingredientes": "Jamon crudo, Mortadela con pistacho, Lomo horneado, salame tandilero, Fontina, Gruyere, Jamon cocido, Bocconcinos",
     "comentario": "",
     "precio": 1750,
     "cantidadComprada": 0},
     {"id": "04",
     "nombre": "Regional",
     "imagen": "images/tabla4.jpg",
     "miniaturas": ["images/tabla4.jpg", "images/tabla3extra.jpg","images/tabla2extra.jpg"],
     "cantidad": "Comen 4, Pican 8",
     "ingredientes": "Jamon crudo, Jamon cocido, Gruyere, Leber, Mar del Plata, Bondiola, Queso ahumado, Lomo embuchado, Parmesano, Roquefort, Brie",
     "comentario": "",
     "precio": 2000,
     "cantidadComprada": 0}

]

let USUARIOS = [];